---
title: "ASYCUDA data exploration"
author: "Derrick Theophille and Lycelle Registe"
date: 2023-07-30

format: 
  html:
    toc: true
    number-sections: true
    fig_caption: false
    
execute: 
  echo: true
  message: false
  warning: false
---

```{r}
#| label: Packages
#| echo: false
  library(tidyverse)
  library(readxl)
  library(janitor)
  library(scales)
  library(knitr)
library(here)
```

# Introduction

# Results 

```{r}
#| label: Import-Data
#| echo: false 

# Importing fresh commodity import data
import_fresh <- read_excel(here("00_raw_data", "ASYVUDA", "import fresh.xls"), 
    sheet = "JULY 2022- JUNE 2023") %>%
  # Standardizing the variable names for use in R
  clean_names() |> 
  # Correct variable names
  rename(origin = orgin) |> 
  # Converting character variables to factor 
  mutate(across(c(tariff_code, description, origin), as.factor)) |> 
  mutate(hs_category_code = str_sub(tariff_code, 1, 4))
```

```{r}
#| label: Import-HS-Codes-Data
#| echo: false 

hs_codes_list <- read_delim(here("00_raw_data", "ASYVUDA", "hs_codes_list.csv"), 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)
```

```{r}
#| label: Merged-Data
#| echo: false 

# Merging Import Fresh Data with HS Code Data
revised_data_set <- import_fresh |> 
  left_join(hs_codes_list, by = join_by(hs_category_code)) |> 
  rename(sub_category = description.x,
         category = description.y) |> 
  # Change order of variables
  select(hs_category_code, tariff_code, category, sub_category, origin, weight_kg, cif_value_ecd) %>% 
  # Reclassify commodities 
  mutate(classification = case_when(
    hs_category_code %in% c("0201", "0202") ~ "Cattle",
    hs_category_code %in% c("0203") ~ "Pigs",
    hs_category_code %in% c("0204") ~ "Sheep or goats",
    hs_category_code %in% c("0207") ~ "Poultry",
    hs_category_code %in% c("0210", "0208", "0206", "0209") ~ "Other meat",
    hs_category_code %in% c("0701") ~ "White potatoes",
    hs_category_code %in% c("0703") ~ sub_category,
    grepl("^03", hs_category_code) ~ "Fish",
    grepl("beans|peas", sub_category, ignore.case = TRUE) & !grepl("blend", sub_category) ~ "Peas and beans",
    grepl("^07", hs_category_code)  ~ "Vegetables",
    hs_category_code %in% c("0801", "0802") ~ "Nuts",
    hs_category_code %in% c("0804", "0806", "0807", "0808", 
                              "0809", "0810", "0811", "0812", "0813", "0814") ~ "Fruits",
    hs_category_code == "0901" ~ "Coffee",
    hs_category_code == "0902" ~ "Tea",
    hs_category_code == "0904" ~ "Peppers (processed)",
    hs_category_code %in% c("0905", "0906", "0907", "0908", 
                              "0909", "0910") ~ "Spices"
  ))
```

```{r}
#| label: Plot
#| echo: false

ggplot(revised_data_set, aes(x = category, y = weight_kg)) + 
  geom_col() +
  coord_flip()
```

